package ADO2_Atividades.Interface;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.time.Instant;
import javax.swing.*;

/** por Rafael Ferreira Goulart **/

public class JF_Menu extends javax.swing.JFrame {

    /**
     * Creates new form JF_Menu
     */
    public JF_Menu() {
        initComponents();
        String();
    }
    
    public void String() {
        Date date = new Date();
        jLabel_Data.setText(date.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_menu = new javax.swing.JPanel();
        jLabel_titulo = new javax.swing.JLabel();
        jPanel_criador = new javax.swing.JPanel();
        jLabel_criador = new javax.swing.JLabel();
        jLabel_Data = new javax.swing.JLabel();
        jButton_atv1 = new javax.swing.JButton();
        jButton_atv2 = new javax.swing.JButton();
        jButton_atv3 = new javax.swing.JButton();
        jButton_atv4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 300));

        jPanel_menu.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_menu.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel_menu.setVerifyInputWhenFocusTarget(false);

        jLabel_titulo.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel_titulo.setText("Menu de Atividades - Projeto integrador");

        jPanel_criador.setBackground(new java.awt.Color(153, 153, 255));
        jPanel_criador.setPreferredSize(new java.awt.Dimension(400, 25));

        jLabel_criador.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel_criador.setText("por Rafael Ferreira Goulart");

        jLabel_Data.setFont(new java.awt.Font("Yu Gothic", 3, 12)); // NOI18N
        jLabel_Data.setText("01/2000");

        javax.swing.GroupLayout jPanel_criadorLayout = new javax.swing.GroupLayout(jPanel_criador);
        jPanel_criador.setLayout(jPanel_criadorLayout);
        jPanel_criadorLayout.setHorizontalGroup(
            jPanel_criadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_criadorLayout.createSequentialGroup()
                .addComponent(jLabel_Data, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addGap(28, 28, 28)
                .addComponent(jLabel_criador)
                .addContainerGap())
        );
        jPanel_criadorLayout.setVerticalGroup(
            jPanel_criadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_criadorLayout.createSequentialGroup()
                .addGroup(jPanel_criadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_criador, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Data))
                .addGap(2, 2, 2))
        );

        jButton_atv1.setBackground(new java.awt.Color(153, 153, 255));
        jButton_atv1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton_atv1.setText("Atividade 1");
        jButton_atv1.setToolTipText("Dados 3 valores reais (float ou double) imprimir o valor do produto destes valores");
        jButton_atv1.setBorder(null);
        jButton_atv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atv1ActionPerformed(evt);
            }
        });

        jButton_atv2.setBackground(new java.awt.Color(153, 153, 255));
        jButton_atv2.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton_atv2.setText("Atividade 2");
        jButton_atv2.setToolTipText("Dado um valor inteiro N imprimir os 3 primeiros múltiplos deste valor");
        jButton_atv2.setBorder(null);
        jButton_atv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atv2ActionPerformed(evt);
            }
        });

        jButton_atv3.setBackground(new java.awt.Color(153, 153, 255));
        jButton_atv3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton_atv3.setText("Atividade 3");
        jButton_atv3.setToolTipText("Dado um valor inteiro de 1 até 10, imprimir a “tabela” da tabuada deste valor");
        jButton_atv3.setBorder(null);
        jButton_atv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atv3ActionPerformed(evt);
            }
        });

        jButton_atv4.setBackground(new java.awt.Color(153, 153, 255));
        jButton_atv4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jButton_atv4.setText("Atividade 4");
        jButton_atv4.setToolTipText("Dado um nome (String), imprimir a quantidade de caracteres deste nome");
        jButton_atv4.setBorder(null);
        jButton_atv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atv4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADO 2");

        javax.swing.GroupLayout jPanel_menuLayout = new javax.swing.GroupLayout(jPanel_menu);
        jPanel_menu.setLayout(jPanel_menuLayout);
        jPanel_menuLayout.setHorizontalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_criador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_titulo)
                    .addComponent(jButton_atv3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_atv4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_atv2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_atv1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_menuLayout.setVerticalGroup(
            jPanel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_menuLayout.createSequentialGroup()
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_criador, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_atv1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_atv2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_atv3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_atv4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_atv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atv4ActionPerformed
        JF_Quarta abrir = new JF_Quarta();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_atv4ActionPerformed

    private void jButton_atv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atv3ActionPerformed
        JF_Terceira abrir = new JF_Terceira();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_atv3ActionPerformed

    private void jButton_atv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atv2ActionPerformed
        JF_Segunda abrir = new JF_Segunda();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_atv2ActionPerformed

    private void jButton_atv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atv1ActionPerformed
        JF_Primeira abrir = new JF_Primeira();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton_atv1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_atv1;
    private javax.swing.JButton jButton_atv2;
    private javax.swing.JButton jButton_atv3;
    private javax.swing.JButton jButton_atv4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Data;
    private javax.swing.JLabel jLabel_criador;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_criador;
    private javax.swing.JPanel jPanel_menu;
    // End of variables declaration//GEN-END:variables
}
